remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

title: Generative AI Training Course
description: A comprehensive course on Generative AI and Prompt Engineering
show_downloads: false

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - module1/theory.md
  - module2/theory.md
